import { ResumeData } from "@/interfaces/resume";
import { TemplateConfig } from "@/interfaces/templates";

/**
 * Default template configuration for resume preview
 * This is used when no template is selected by the user
 */
export const defaultTemplateConfig: TemplateConfig = {
	id: "default-template",
	name: "Professional",
	description: "Clean and professional resume template",
	thumbnail: "",
	categories: ["professional", "modern"],
	pricing: {
		isPaid: false,
		tier: "free",
	},
	permissions: {
		canChangeColors: true,
		canChangeFonts: true,
		canChangeLayout: true,
		canChangeSections: true,
		canChangeSectionConfig: true,
		canChangeSpacing: true,
		canChangeBorders: true,
	},
	layout: {
		type: "two-column-left-heavy",
		columnRatio: {
			left: 65,
			right: 35,
		},
		gap: "1.5rem",
		sections: [
			{ type: "personal-info", position: "full-width", order: 0, visibility: true, required: true },
			{ type: "experience", position: "left", order: 1, visibility: true, required: false },
			{ type: "education", position: "left", order: 2, visibility: true, required: false },
			{ type: "projects", position: "left", order: 3, visibility: true, required: false },
			{ type: "skills", position: "right", order: 1, visibility: true, required: false },
			{ type: "certifications", position: "right", order: 2, visibility: true, required: false },
			{ type: "achievements", position: "right", order: 3, visibility: true, required: false },
		],
	},
	colors: {
		primary: "#2563eb",
		secondary: "#3b82f6",
		accent: "#60a5fa",
		text: "#1e293b",
		textLight: "#64748b",
		background: "#ffffff",
		border: "#e2e8f0",
		link: "#2563eb",
	},
	typography: {
		headingFont: "Geist",
		bodyFont: "Geist",
		nameSize: "3xl",
		nameWeight: "bold",
		headingSize: "xl",
		headingWeight: "bold",
		subheadingSize: "base",
		subheadingWeight: "semibold",
		lineHeight: "normal",
		headingUppercase: false,
		headingUnderline: true,
		showIcons: true,
		showDividers: true,
	},
	spacing: {
		section: "1.5rem",
		item: "1rem",
		margin: "1.5rem",
		padding: "1.5rem",
	},
	borders: {
		style: "solid",
		width: "1px",
		color: "#e2e8f0",
		radius: "0.5rem",
	},
	personalInfoConfig: {
		showWebsite: true,
		showLinks: true,
		showSummary: true,
		summaryPosition: "below-contact",
		contactLayout: "horizontal",
		showIcons: true,
	},
	experienceConfig: {
		showLocation: true,
		showDescription: false,
		showAchievements: true,
		showSkillsUsed: false,
		dateFormat: "short",
		achievementsAsBullets: true,
	},
	educationConfig: {
		showLocation: true,
		showGrade: true,
		showAchievements: false,
		showCoursework: false,
		dateFormat: "short",
		achievementsAsBullets: true,
	},
	skillsConfig: {
		displayFormat: "bars",
		showLevel: true,
		groupByCategory: true,
		showYearsOfExperience: false,
		technicalSkillsLabel: "Technical Skills",
		softSkillsLabel: "Soft Skills",
		languagesLabel: "Languages",
	},
	projectsConfig: {
		showSubtitle: true,
		showDescription: true,
		showTechnologies: true,
		showLinks: true,
		showDates: true,
		showHighlights: true,
		dateFormat: "short",
		highlightsAsBullets: true,
	},
	certificationsConfig: {
		showIssueDate: true,
		showExpirationDate: false,
		showCredentialUrl: true,
		dateFormat: "short",
		urlAsQRCode: false,
	},
	achievementsConfig: {
		showIssuer: true,
		showDate: true,
		showDescription: true,
		dateFormat: "short",
	},
	metadata: {
		createdBy: "system",
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		isPublished: true,
		isActive: true,
		usageCount: 0,
		rating: 0,
		tags: ["professional", "modern", "clean"],
	},
};


// Dummy resume data for realistic preview - properly typed
export const dummyData: ResumeData = {
	name: "Professional Resume",
	description: "A comprehensive professional resume showcasing 8+ years of experience",
	personalInfo: {
		fullName: "Sarah Johnson",
		email: "sarah.johnson@email.com",
		phone: "+1 (555) 123-4567",
		location: "San Francisco, CA",
		website: "sarahjohnson.com",
		links: [
			{ label: "LinkedIn", url: "linkedin.com/in/sarahjohnson" },
			{ label: "GitHub", url: "github.com/sarahjohnson" },
		],
		summary:
			"Results-driven Senior Software Engineer with 8+ years of experience in full-stack development, cloud architecture, and team leadership. Proven track record of delivering scalable solutions that drive business growth and improve user experience. Expert in modern web technologies, microservices architecture, and agile methodologies.",
	},
	experience: [
		{
			id: "exp-1",
			order: 1,
			jobTitle: "Senior Software Engineer",
			company: "Tech Corp",
			location: "San Francisco, CA",
			startDate: new Date(2022, 0), // Jan 2022
			endDate: undefined,
			currentlyWorking: true,
			achievements: [
				"Led development of microservices architecture serving 2M+ users with 99.9% uptime",
				"Reduced API response time by 40% through code optimization and database indexing",
				"Mentored team of 5 junior developers, improving code quality and delivery speed by 30%",
				"Architected serverless infrastructure on AWS, reducing hosting costs by $50K annually",
			],
			skillsUsed: ["React", "Node.js", "AWS", "Docker"],
		},
		{
			id: "exp-2",
			order: 2,
			jobTitle: "Software Engineer",
			company: "StartupXYZ",
			location: "Remote",
			startDate: new Date(2019, 5), // Jun 2019
			endDate: new Date(2021, 11), // Dec 2021
			currentlyWorking: false,
			achievements: [
				"Built responsive web applications using React and Node.js, serving 500K+ active users",
				"Implemented CI/CD pipeline with GitHub Actions, reducing deployment time by 60%",
				"Developed RESTful APIs and GraphQL services for mobile and web clients",
				"Collaborated with product team to deliver features that increased user engagement by 25%",
			],
			skillsUsed: ["React", "Node.js", "GraphQL"],
		},
		{
			id: "exp-3",
			order: 3,
			jobTitle: "Frontend Developer",
			company: "Digital Agency",
			location: "Los Angeles, CA",
			startDate: new Date(2017, 2), // Mar 2017
			endDate: new Date(2019, 4), // May 2019
			currentlyWorking: false,
			achievements: [
				"Created pixel-perfect, responsive websites for 20+ enterprise clients",
				"Improved website performance scores from 60 to 95+ using modern optimization techniques",
				"Implemented automated testing suite achieving 85% code coverage",
			],
			skillsUsed: ["HTML", "CSS", "JavaScript"],
		},
	],
	education: [
		{
			id: "edu-1",
			order: 1,
			degree: "Master of Science in Computer Science",
			institution: "Stanford University",
			location: "Stanford, CA",
			startDate: new Date(2019, 8), // Sep 2019
			endDate: new Date(2021, 5), // Jun 2021
			currentlyStudying: false,
			gradeType: "gpa",
			gradeValue: "3.9",
			achievements: [],
			coursework: [],
		},
		{
			id: "edu-2",
			order: 2,
			degree: "Bachelor of Science in Computer Science",
			institution: "University of California",
			location: "Berkeley, CA",
			startDate: new Date(2015, 8), // Sep 2015
			endDate: new Date(2019, 4), // May 2019
			currentlyStudying: false,
			gradeType: "gpa",
			gradeValue: "3.8",
			achievements: [],
			coursework: [],
		},
	],
	skills: {
		technical: [
			{ name: "JavaScript", level: 10 },
			{ name: "TypeScript", level: 9 },
			{ name: "React", level: 10 },
			{ name: "Next.js", level: 9 },
			{ name: "Vue.js", level: 8 },
			{ name: "Node.js", level: 9 },
			{ name: "Express", level: 8 },
			{ name: "Python", level: 7 },
			{ name: "Django", level: 7 },
			{ name: "PostgreSQL", level: 8 },
			{ name: "MongoDB", level: 8 },
			{ name: "Redis", level: 7 },
			{ name: "AWS", level: 8 },
			{ name: "Docker", level: 9 },
			{ name: "Kubernetes", level: 7 },
			{ name: "GraphQL", level: 8 },
			{ name: "REST APIs", level: 9 },
			{ name: "Git", level: 10 },
		],
		soft: [
			{ name: "Leadership", level: 9 },
			{ name: "Team Management", level: 8 },
			{ name: "Problem Solving", level: 10 },
			{ name: "Communication", level: 9 },
			{ name: "Agile/Scrum", level: 9 },
			{ name: "Code Review", level: 9 },
			{ name: "Mentoring", level: 8 },
			{ name: "Project Planning", level: 8 },
		],
		languages: [
			{ language: "English", proficiency: "Native" },
			{ language: "Spanish", proficiency: "Professional" },
			{ language: "French", proficiency: "Basic" },
		],
	},
	projects: [
		{
			id: "proj-1",
			order: 1,
			name: "E-commerce Platform",
			subtitle: "Full-stack Development",
			description:
				"Built a full-stack e-commerce platform with payment integration, inventory management, and real-time order tracking serving 100K+ monthly users",
			technologies: ["React", "Node.js", "MongoDB", "Stripe", "AWS", "Docker"],
			links: [
				{ label: "Live Demo", url: "https://ecommerce-demo.com" },
				{ label: "GitHub", url: "https://github.com/sarah/ecommerce" },
			],
			startDate: new Date(2023, 0),
			endDate: new Date(2023, 6),
			currentlyWorking: false,
			highlights: [
				"Served 100K+ monthly users",
				"Integrated Stripe payment processing",
				"Real-time order tracking system",
			],
		},
		{
			id: "proj-2",
			order: 2,
			name: "Task Management App",
			subtitle: "Collaborative Tool",
			description:
				"Developed a real-time collaborative task management application with team workspaces, notifications, and analytics dashboard",
			technologies: ["Vue.js", "Firebase", "Tailwind CSS", "TypeScript"],
			links: [
				{ label: "GitHub", url: "https://github.com/sarah/task-manager" },
			],
			startDate: new Date(2022, 6),
			endDate: new Date(2022, 11),
			currentlyWorking: false,
			highlights: [
				"Real-time collaboration features",
				"Team workspace management",
				"Analytics dashboard",
			],
		},
		{
			id: "proj-3",
			order: 3,
			name: "AI-Powered Resume Builder",
			subtitle: "AI Integration",
			description:
				"Created an intelligent resume builder with AI-assisted content generation, template customization, and PDF export functionality",
			technologies: ["Next.js", "OpenAI API", "Prisma", "PostgreSQL"],
			links: [],
			startDate: new Date(2024, 0),
			currentlyWorking: true,
			highlights: [
				"AI-assisted content generation",
				"Multiple template support",
				"PDF export functionality",
			],
		},
		{
			id: "proj-4",
			order: 4,
			name: "Analytics Dashboard",
			subtitle: "Data Visualization",
			description:
				"Built comprehensive analytics platform with real-time data visualization and custom reporting capabilities",
			technologies: ["React", "D3.js", "Node.js", "InfluxDB", "Grafana"],
			links: [],
			startDate: new Date(2021, 8),
			endDate: new Date(2022, 2),
			currentlyWorking: false,
			highlights: [
				"Real-time data visualization",
				"Custom reporting engine",
				"Performance monitoring",
			],
		},
	],
	certifications: [
		{
			id: "cert-1",
			order: 1,
			name: "AWS Certified Solutions Architect - Professional",
			issuingOrganization: "Amazon Web Services",
			issueDate: new Date(2023, 5),
			expirationDate: new Date(2026, 5),
			credentialUrl: "https://aws.amazon.com/verification",
			doesNotExpire: false,
		},
		{
			id: "cert-2",
			order: 2,
			name: "Google Cloud Professional Cloud Architect",
			issuingOrganization: "Google Cloud",
			issueDate: new Date(2023, 3),
			expirationDate: new Date(2025, 3),
			credentialUrl: "https://cloud.google.com/certification",
			doesNotExpire: false,
		},
		{
			id: "cert-3",
			order: 3,
			name: "Professional Scrum Master I (PSM I)",
			issuingOrganization: "Scrum.org",
			issueDate: new Date(2022, 8),
			credentialUrl: "https://scrum.org/certification",
			doesNotExpire: true,
		},
		{
			id: "cert-4",
			order: 4,
			name: "MongoDB Certified Developer",
			issuingOrganization: "MongoDB University",
			issueDate: new Date(2021, 10),
			expirationDate: new Date(2024, 10),
			credentialUrl: "https://university.mongodb.com",
			doesNotExpire: false,
		},
		{
			id: "cert-5",
			order: 5,
			name: "React Advanced Patterns",
			issuingOrganization: "Frontend Masters",
			issueDate: new Date(2021, 6),
			credentialUrl: "https://frontendmasters.com/certificates",
			doesNotExpire: true,
		},
	],
	achievements: [
		{
			id: "ach-1",
			order: 1,
			title: "Best Innovation Award",
			issuer: "Tech Corp",
			date: new Date(2023, 11),
			description:
				"Recognized for developing AI-powered feature that increased user retention by 35%",
		},
		{
			id: "ach-2",
			order: 2,
			title: "Employee of the Year",
			issuer: "Tech Corp",
			date: new Date(2022, 11),
			description:
				"Awarded for exceptional performance and leadership in delivering critical projects",
		},
		{
			id: "ach-3",
			order: 3,
			title: "Hackathon Winner - Best Technical Solution",
			issuer: "StartupXYZ",
			date: new Date(2020, 8),
			description: "Led team to victory with real-time collaboration tool prototype",
		},
		{
			id: "ach-4",
			order: 4,
			title: "Open Source Contributor Recognition",
			issuer: "GitHub",
			date: new Date(2021, 5),
			description: "Contributed to 15+ open source projects with 500+ stars combined",
		},
	],
};