import { ResumeData } from "@/interfaces/resume";

export const dummyResumeBuilderRecord: ResumeData = {
	name: "Full Stack Developer Resume",
	description: "A comprehensive resume showcasing my expertise in modern web development",
	personalInfo: {
		fullName: "John Michael Doe",
		email: "john.doe@example.com",
		phone: "+1 (555) 123-4567",
		location: "San Francisco, CA",
		website: "https://johndoe.dev",
		links: [
			{ label: "LinkedIn", url: "https://linkedin.com/in/johndoe" },
			{ label: "GitHub", url: "https://github.com/johndoe" },
			{ label: "Portfolio", url: "https://johndoe.dev" },
		],
		summary: "Passionate Full Stack Developer with 5+ years of experience building scalable web applications. Proficient in React, Node.js, and cloud technologies. Strong track record of delivering high-quality solutions that drive business growth and improve user experience.",
	},
	experience: [
		{
			id: "exp-1",
			order: 0,
			jobTitle: "Senior Full Stack Developer",
			company: "Tech Solutions Inc",
			location: "San Francisco, CA",
			startDate: new Date("2022-01-01"),
			endDate: undefined,
			currentlyWorking: true,
			description: "Leading development of enterprise-level web applications",
			achievements: [
				"Led a team of 5 developers in building a microservices architecture",
				"Reduced application load time by 60% through optimization",
				"Implemented CI/CD pipeline reducing deployment time by 75%",
				"Mentored junior developers and conducted code reviews",
			],
			skillsUsed: ["React", "Node.js", "TypeScript", "AWS", "Docker", "MongoDB"],
		},
		{
			id: "exp-2",
			order: 1,
			jobTitle: "Full Stack Developer",
			company: "Digital Innovations LLC",
			location: "New York, NY",
			startDate: new Date("2019-06-01"),
			endDate: new Date("2021-12-31"),
			currentlyWorking: false,
			description: "Developed customer-facing web applications",
			achievements: [
				"Built responsive web applications serving 100K+ users",
				"Integrated third-party APIs to enhance functionality",
				"Improved code quality by implementing testing frameworks",
			],
			skillsUsed: ["JavaScript", "Vue.js", "Python", "PostgreSQL", "Redis"],
		},
	],
	education: [
		{
			id: "edu-1",
			order: 0,
			degree: "Bachelor of Science in Computer Science",
			institution: "Stanford University",
			location: "Stanford, CA",
			startDate: new Date("2015-09-01"),
			endDate: new Date("2019-05-31"),
			currentlyStudying: false,
			gradeType: "gpa",
			gradeValue: "3.8",
			achievements: [
				"Dean's List - 6 semesters",
				"President of Computer Science Club",
				"Best Capstone Project Award",
			],
			coursework: [
				"Data Structures & Algorithms",
				"Web Development",
				"Database Systems",
				"Machine Learning",
				"Software Engineering",
			],
		},
	],
	skills: {
		technical: [
			{ name: "JavaScript", level: 9 },
			{ name: "TypeScript", level: 8 },
			{ name: "React", level: 9 },
			{ name: "Next.js", level: 8 },
			{ name: "Node.js", level: 8 },
			{ name: "Python", level: 7 },
			{ name: "PostgreSQL", level: 7 },
			{ name: "MongoDB", level: 8 },
			{ name: "AWS", level: 6 },
			{ name: "Docker", level: 7 },
			{ name: "Git", level: 9 },
			{ name: "REST APIs", level: 8 },
		],
		soft: [
			{ name: "Leadership", level: 8 },
			{ name: "Problem Solving", level: 9 },
			{ name: "Communication", level: 9 },
			{ name: "Team Collaboration", level: 8 },
			{ name: "Agile Methodology", level: 7 },
			{ name: "Time Management", level: 8 },
		],
		languages: [
			{ language: "English", proficiency: "Native" },
			{ language: "Spanish", proficiency: "Professional" },
			{ language: "French", proficiency: "Basic" },
		],
	},
	projects: [
		{
			id: "proj-1",
			order: 0,
			name: "E-commerce Platform",
			subtitle: "Full-Stack Web Application",
			description: "Built a modern e-commerce platform with real-time inventory management",
			technologies: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Tailwind CSS"],
			links: [
				{ label: "Live Site", url: "https://myecommerce.com" },
				{ label: "GitHub", url: "https://github.com/johndoe/ecommerce" },
			],
			startDate: new Date("2023-01-01"),
			endDate: new Date("2023-06-30"),
			currentlyWorking: false,
			highlights: [
				"Processed $500K+ in transactions within first 3 months",
				"Achieved 99.9% uptime with robust error handling",
				"Integrated payment gateway with 100% success rate",
			],
		},
		{
			id: "proj-2",
			order: 1,
			name: "Task Management Dashboard",
			subtitle: "Productivity Tool for Teams",
			description: "Collaborative project management tool with real-time updates",
			technologies: ["React", "Node.js", "Socket.io", "MongoDB", "Redux"],
			links: [
				{ label: "Demo", url: "https://taskmanager-demo.com" },
			],
			startDate: new Date("2022-06-01"),
			endDate: undefined,
			currentlyWorking: true,
			highlights: [
				"Improved team productivity by 40%",
				"Supports 1000+ concurrent users",
				"Real-time collaboration features",
			],
		},
	],
	certifications: [
		{
			id: "cert-1",
			order: 0,
			name: "AWS Certified Solutions Architect - Associate",
			issuingOrganization: "Amazon Web Services",
			issueDate: new Date("2023-03-15"),
			expirationDate: new Date("2026-03-15"),
			doesNotExpire: false,
			credentialUrl: "https://aws.amazon.com/verification/12345",
		},
		{
			id: "cert-2",
			order: 1,
			name: "MongoDB Certified Developer",
			issuingOrganization: "MongoDB University",
			issueDate: new Date("2022-08-20"),
			expirationDate: undefined,
			doesNotExpire: true,
			credentialUrl: "https://university.mongodb.com/cert/67890",
		},
	],
	achievements: [
		{
			id: "ach-1",
			order: 0,
			title: "Employee of the Year 2023",
			issuer: "Tech Solutions Inc",
			date: new Date("2023-12-15"),
			description: "Recognized for outstanding contribution to company growth, exceptional technical leadership, and mentoring team members. Led multiple successful projects that increased revenue by 35%.",
		},
		{
			id: "ach-2",
			order: 1,
			title: "Best Innovation Award",
			issuer: "Digital Innovations LLC",
			date: new Date("2021-11-10"),
			description: "Awarded for developing an innovative solution that automated manual processes, saving the company 200+ hours per month and improving operational efficiency significantly.",
		},
	],
};