import { ResumeData } from "@/interfaces/resume";

export const dummyResumeBuilderRecord: ResumeData = {
	name: "Full Stack Developer Resume",
	description: "A comprehensive resume showcasing my expertise in modern web development",
	personalInfo: {
		fullName: "John Michael Doe",
		email: "john.doe@example.com",
		phone: "+1 (555) 123-4567",
		location: "San Francisco, CA",
		website: "https://johndoe.dev",
		links: [
			{ label: "LinkedIn", url: "https://linkedin.com/in/johndoe" },
			{ label: "GitHub", url: "https://github.com/johndoe" },
			{ label: "Portfolio", url: "https://johndoe.dev" },
		],
		summary: "Passionate Full Stack Developer with 5+ years of experience building scalable web applications. Proficient in React, Node.js, and cloud technologies. Strong track record of delivering high-quality solutions that drive business growth and improve user experience.",
	},
	experience: [
		{
			id: "exp-1",
			order: 0,
			jobTitle: "Senior Full Stack Developer",
			company: "Tech Solutions Inc",
			location: "San Francisco, CA",
			startDate: new Date("2022-01-01"),
			endDate: undefined,
			currentlyWorking: true,
			description: "Leading development of enterprise-level web applications",
			achievements: [
				"Led a team of 5 developers in building a microservices architecture",
				"Reduced application load time by 60% through optimization",
				"Implemented CI/CD pipeline reducing deployment time by 75%",
				"Mentored junior developers and conducted code reviews",
			],
			skillsUsed: ["React", "Node.js", "TypeScript", "AWS", "Docker", "MongoDB"],
		},
		{
			id: "exp-2",
			order: 1,
			jobTitle: "Full Stack Developer",
			company: "Digital Innovations LLC",
			location: "New York, NY",
			startDate: new Date("2019-06-01"),
			endDate: new Date("2021-12-31"),
			currentlyWorking: false,
			description: "Developed customer-facing web applications",
			achievements: [
				"Built responsive web applications serving 100K+ users",
				"Integrated third-party APIs to enhance functionality",
				"Improved code quality by implementing testing frameworks",
			],
			skillsUsed: ["JavaScript", "Vue.js", "Python", "PostgreSQL", "Redis"],
		},
		{
			id: "exp-3",
			order: 2,
			jobTitle: "Software Developer",
			company: "StartupHub Technologies",
			location: "Austin, TX",
			startDate: new Date("2018-03-01"),
			endDate: new Date("2019-05-31"),
			currentlyWorking: false,
			description: "Contributed to development of SaaS products for enterprise clients",
			achievements: [
				"Developed RESTful APIs handling 10M+ requests daily",
				"Collaborated with cross-functional teams to deliver features on time",
				"Reduced bug count by 45% through comprehensive testing",
				"Optimized database queries improving response time by 50%",
			],
			skillsUsed: ["React", "Express.js", "MySQL", "Jest", "GraphQL"],
		},
		{
			id: "exp-4",
			order: 3,
			jobTitle: "Junior Web Developer",
			company: "WebCraft Solutions",
			location: "Remote",
			startDate: new Date("2017-06-01"),
			endDate: new Date("2018-02-28"),
			currentlyWorking: false,
			description: "Assisted in building modern websites and web applications for clients",
			achievements: [
				"Developed 15+ responsive websites for various clients",
				"Implemented modern UI/UX designs using latest web standards",
				"Collaborated with designers to transform mockups into functional websites",
				"Maintained client websites ensuring 99% uptime",
			],
			skillsUsed: ["HTML5", "CSS3", "JavaScript", "jQuery", "Bootstrap", "WordPress"],
		},
	],
	education: [
		{
			id: "edu-1",
			order: 0,
			degree: "Bachelor of Science in Computer Science",
			institution: "Stanford University",
			location: "Stanford, CA",
			startDate: new Date("2015-09-01"),
			endDate: new Date("2019-05-31"),
			currentlyStudying: false,
			gradeType: "gpa",
			gradeValue: "3.8",
			achievements: [
				"Dean's List - 6 semesters",
				"President of Computer Science Club",
				"Best Capstone Project Award",
			],
			coursework: [
				"Data Structures & Algorithms",
				"Web Development",
				"Database Systems",
				"Machine Learning",
				"Software Engineering",
			],
		},
		{
			id: "edu-2",
			order: 1,
			degree: "Master of Science in Software Engineering",
			institution: "MIT",
			location: "Cambridge, MA",
			startDate: new Date("2019-09-01"),
			endDate: new Date("2021-05-31"),
			currentlyStudying: false,
			gradeType: "gpa",
			gradeValue: "3.9",
			achievements: [
				"Graduate Research Assistant",
				"Published 2 research papers on distributed systems",
				"Outstanding Graduate Student Award",
			],
			coursework: [
				"Distributed Systems",
				"Cloud Computing",
				"Advanced Algorithms",
				"Software Architecture",
				"DevOps & CI/CD",
			],
		},
		{
			id: "edu-3",
			order: 2,
			degree: "Full Stack Web Development Bootcamp",
			institution: "General Assembly",
			location: "San Francisco, CA",
			startDate: new Date("2017-01-01"),
			endDate: new Date("2017-04-30"),
			currentlyStudying: false,
			gradeType: "percentage",
			gradeValue: "95",
			achievements: [
				"Top 5% of cohort",
				"Best Final Project Award",
				"Teaching Assistant for 2 subsequent cohorts",
			],
			coursework: [
				"JavaScript & ES6",
				"React & Redux",
				"Node.js & Express",
				"MongoDB & PostgreSQL",
				"RESTful API Design",
			],
		},
		{
			id: "edu-4",
			order: 3,
			degree: "Online Specialization in Cloud Architecture",
			institution: "Coursera - University of Illinois",
			location: "Online",
			startDate: new Date("2020-06-01"),
			endDate: new Date("2020-12-31"),
			currentlyStudying: false,
			gradeType: "percentage",
			gradeValue: "98",
			achievements: [
				"Completed with distinction",
				"Built 5 cloud-native applications",
				"Earned professional certificate",
			],
			coursework: [
				"Cloud Computing Concepts",
				"Microservices Architecture",
				"Kubernetes & Docker",
				"AWS & Azure Services",
				"Serverless Computing",
			],
		},
	],
	skills: {
		technical: [
			{ name: "JavaScript", level: 9 },
			{ name: "TypeScript", level: 8 },
			{ name: "React", level: 9 },
			{ name: "Next.js", level: 8 },
			{ name: "Node.js", level: 8 },
			{ name: "Python", level: 7 },
			{ name: "PostgreSQL", level: 7 },
			{ name: "MongoDB", level: 8 },
			{ name: "AWS", level: 6 },
			{ name: "Docker", level: 7 },
			{ name: "Git", level: 9 },
			{ name: "REST APIs", level: 8 },
		],
		soft: [
			{ name: "Leadership", level: 8 },
			{ name: "Problem Solving", level: 9 },
			{ name: "Communication", level: 9 },
			{ name: "Team Collaboration", level: 8 },
			{ name: "Agile Methodology", level: 7 },
			{ name: "Time Management", level: 8 },
		],
		languages: [
			{ language: "English", proficiency: "Native" },
			{ language: "Spanish", proficiency: "Professional" },
			{ language: "French", proficiency: "Basic" },
		],
	},
	projects: [
		{
			id: "proj-1",
			order: 0,
			name: "E-commerce Platform",
			subtitle: "Full-Stack Web Application",
			description: "Built a modern e-commerce platform with real-time inventory management",
			technologies: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Tailwind CSS"],
			links: [
				{ label: "Live Site", url: "https://myecommerce.com" },
				{ label: "GitHub", url: "https://github.com/johndoe/ecommerce" },
			],
			startDate: new Date("2023-01-01"),
			endDate: new Date("2023-06-30"),
			currentlyWorking: false,
			highlights: [
				"Processed $500K+ in transactions within first 3 months",
				"Achieved 99.9% uptime with robust error handling",
				"Integrated payment gateway with 100% success rate",
			],
		},
		{
			id: "proj-2",
			order: 1,
			name: "Task Management Dashboard",
			subtitle: "Productivity Tool for Teams",
			description: "Collaborative project management tool with real-time updates",
			technologies: ["React", "Node.js", "Socket.io", "MongoDB", "Redux"],
			links: [
				{ label: "Demo", url: "https://taskmanager-demo.com" },
			],
			startDate: new Date("2022-06-01"),
			endDate: undefined,
			currentlyWorking: true,
			highlights: [
				"Improved team productivity by 40%",
				"Supports 1000+ concurrent users",
				"Real-time collaboration features",
			],
		},
	],
	certifications: [
		{
			id: "cert-1",
			order: 0,
			name: "AWS Certified Solutions Architect - Associate",
			issuingOrganization: "Amazon Web Services",
			issueDate: new Date("2023-03-15"),
			expirationDate: new Date("2026-03-15"),
			doesNotExpire: false,
			credentialUrl: "https://aws.amazon.com/verification/12345",
		},
		{
			id: "cert-2",
			order: 1,
			name: "MongoDB Certified Developer",
			issuingOrganization: "MongoDB University",
			issueDate: new Date("2022-08-20"),
			expirationDate: undefined,
			doesNotExpire: true,
			credentialUrl: "https://university.mongodb.com/cert/67890",
		},
		{
			id: "cert-3",
			order: 2,
			name: "Professional Scrum Master I (PSM I)",
			issuingOrganization: "Scrum.org",
			issueDate: new Date("2022-05-10"),
			expirationDate: undefined,
			doesNotExpire: true,
			credentialUrl: "https://scrum.org/certificates/11223",
		},
		{
			id: "cert-4",
			order: 3,
			name: "Google Cloud Professional Cloud Architect",
			issuingOrganization: "Google Cloud",
			issueDate: new Date("2023-09-01"),
			expirationDate: new Date("2025-09-01"),
			doesNotExpire: false,
			credentialUrl: "https://google.com/cloud/certification/44556",
		},
	],
	achievements: [
		{
			id: "ach-1",
			order: 0,
			title: "Employee of the Year 2023",
			issuer: "Tech Solutions Inc",
			date: new Date("2023-12-15"),
			description: "Recognized for outstanding contribution to company growth, exceptional technical leadership, and mentoring team members. Led multiple successful projects that increased revenue by 35%.",
		},
		{
			id: "ach-2",
			order: 1,
			title: "Best Innovation Award",
			issuer: "Digital Innovations LLC",
			date: new Date("2021-11-10"),
			description: "Awarded for developing an innovative solution that automated manual processes, saving the company 200+ hours per month and improving operational efficiency significantly.",
		},
		{
			id: "ach-3",
			order: 2,
			title: "Hackathon Winner - TechCrunch Disrupt 2022",
			issuer: "TechCrunch",
			date: new Date("2022-09-20"),
			description: "Led a team of 4 developers to win first place out of 150+ teams. Built an AI-powered analytics platform in 48 hours that impressed judges with its innovation and technical implementation.",
		},
		{
			id: "ach-4",
			order: 3,
			title: "Open Source Contributor of the Month",
			issuer: "GitHub",
			date: new Date("2023-06-01"),
			description: "Recognized for significant contributions to popular open-source projects including React, Next.js, and TypeScript. Contributed over 50 pull requests fixing critical bugs and adding new features used by millions of developers worldwide.",
		},
	],
};