import { TemplateConfig, TemplateEnum } from "@/interfaces/templates";

export const classicConfig: TemplateConfig = {
	id: TemplateEnum.CLASSIC,
	name: "Classic Professional",
	description:
		"A timeless, professional resume template inspired by LaTeX layouts, perfect for traditional industries and ATS systems",
	category: "Professional",

	pricing: {
		isPaid: false,
		prices: {},
	},

	layout: {
		type: "single-column",
		pageSize: "A4",
		orientation: "portrait",
	},

	sections: [
		{
			id: "personal-info",
			type: "personalInfo",
			label: "Contact Information",
			position: "full-width",
			order: 1,
			visible: true,
			required: true,
			styling: {
				fontSize: 16,
				fontWeight: "bold",
				color: "#000000",
				spacing: 20,
				showIcons: false,
				showDivider: false,
			},
		},
		{
			id: "summary",
			type: "summary",
			label: "Professional Summary",
			position: "full-width",
			order: 2,
			visible: true,
			required: false,
			styling: {
				fontSize: 14,
				fontWeight: "normal",
				color: "#374151",
				spacing: 12,
				showIcons: false,
				showDivider: true,
			},
		},
		{
			id: "experience",
			type: "experience",
			label: "Experience",
			position: "full-width",
			order: 3,
			visible: true,
			required: true,
			styling: {
				fontSize: 14,
				fontWeight: "bold",
				color: "#000000",
				spacing: 12,
				showIcons: false,
				showDivider: true,
			},
		},
		{
			id: "education",
			type: "education",
			label: "Education",
			position: "full-width",
			order: 4,
			visible: true,
			required: true,
			styling: {
				fontSize: 14,
				fontWeight: "bold",
				color: "#000000",
				spacing: 12,
				showIcons: false,
				showDivider: true,
			},
		},
		{
			id: "projects",
			type: "projects",
			label: "Projects",
			position: "full-width",
			order: 5,
			visible: true,
			required: false,
			styling: {
				fontSize: 14,
				fontWeight: "bold",
				color: "#000000",
				spacing: 12,
				showIcons: false,
				showDivider: true,
			},
		},
		{
			id: "skills",
			type: "skills",
			label: "Technologies",
			position: "full-width",
			order: 6,
			visible: true,
			required: true,
			styling: {
				fontSize: 14,
				fontWeight: "bold",
				color: "#000000",
				spacing: 12,
				showIcons: false,
				showDivider: true,
			},
		},
		{
			id: "certifications",
			type: "certifications",
			label: "Certifications",
			position: "full-width",
			order: 7,
			visible: true,
			required: false,
			styling: {
				fontSize: 14,
				fontWeight: "bold",
				color: "#000000",
				spacing: 12,
				showIcons: false,
				showDivider: true,
			},
		},
		{
			id: "achievements",
			type: "achievements",
			label: "Achievements",
			position: "full-width",
			order: 8,
			visible: true,
			required: false,
			styling: {
				fontSize: 14,
				fontWeight: "bold",
				color: "#000000",
				spacing: 12,
				showIcons: false,
				showDivider: true,
			},
		},
	],

	style: {
		primaryColor: "#000000",
		secondaryColor: "#374151",
		accentColor: "#6B7280",
		textColor: "#374151",
		backgroundColor: "#ffffff",

		fontFamily: "Times New Roman, serif",
		headingFont: "Times New Roman, serif",
		bodyFont: "Times New Roman, serif",
		fontSize: {
			heading: 20,
			subheading: 14,
			body: 11,
			small: 10,
		},

		padding: 32,
		margin: 16,
		sectionSpacing: 16,

		borderRadius: 0,
		showBorders: false,
		showShadow: false,
	},

	createdBy: "system",
	createdAt: new Date(),
	updatedAt: new Date(),
	isPublished: true,
	isActive: true,
	usageCount: 0,
	rating: 4.5,
	tags: [
		"professional",
		"classic",
		"traditional",
		"ats-friendly",
		"latex-inspired",
	],
	version: "1.0.0",
};

export default classicConfig;
